logger:
  kind: console
  level: debug
backendKind: postgres
backendConfig:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  databaseName: postgres
  migrationsDir: "file://./scripts/psql/migrations"
