name: pull requests

on:
  pull_request:
    paths:
      - '.github/**'
      - 'api/**'
      - 'cmd/**'
      - 'deployments/**'
      - 'internal/**'
      - 'pkg/**'
      - 'scripts/**'
      - 'go.*'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build .
